# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixdb', '0002_auto_20171005_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='netflix',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
