# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixdb', '0003_netflix_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField()),
                ('contact_number', models.IntegerField()),
                ('contact_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_id', models.IntegerField()),
                ('personal_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_id', models.IntegerField()),
                ('director_soap', models.CharField(max_length=50)),
                ('director_movie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.IntegerField()),
                ('genre_soap', models.CharField(max_length=50)),
                ('genre_movie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('location_city', models.CharField(max_length=50)),
                ('location_state', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('movie_title', models.CharField(max_length=50)),
                ('genre_id', models.IntegerField()),
                ('director_id', models.IntegerField()),
                ('movie_cast', models.CharField(max_length=50)),
                ('release_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.IntegerField()),
                ('name_firstname', models.CharField(max_length=50)),
                ('name_lastname', models.CharField(max_length=50)),
                ('name_middlename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('payment_type', models.CharField(max_length=50)),
                ('payment_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_id', models.IntegerField()),
                ('personal_gender', models.CharField(max_length=50)),
                ('personal_dob', models.DateTimeField()),
                ('pname_id', models.IntegerField()),
                ('contact_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.IntegerField()),
                ('payment_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.IntegerField()),
                ('release_soap', models.DateTimeField()),
                ('release_movie', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Soap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soap_id', models.IntegerField()),
                ('soap_title', models.CharField(max_length=50)),
                ('genre_id', models.IntegerField()),
                ('director_id', models.IntegerField()),
                ('soap_cast', models.CharField(max_length=50)),
                ('release_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('details_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('plan_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Netflix',
        ),
    ]
